name: Variables
run-name: Â¡Estoy aprendiendo a usar variables!
on: 
  workflow_dispatch
env:
  dia_semana: "todos los dias"
jobs:
  variables-env:
    runs-on: ubuntu-lastest
    env:
      tipo_amor: " el mas tierno"
    steps:
      - name: correr en env
        run: echo "yo ${{ vars.NOMBRE }} $sentimiento a ${{ vars.PAREJA }} con $tipo_amor amor $dia_semana"
        env: 
          sentimiento: amo
